export const POPULATION: any[] = [
    // {type: 'used', percent: 2704659},
    // {type: 'unused', percent: 4499890},


    {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96763",
        "BeneCategory": "Preventative Care",
        "BeneSubcategory": "Prostate exam",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96763",
        "BeneCategory": "Preventative Care",
        "BeneSubcategory": "Prostate exam",
        "TotalPaidByBenefit": "299.0000",
        "ServiceCount": "1",
        "ClaimCount": "1",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96764",
        "BeneCategory": "Preventative Care",
        "BeneSubcategory": "Gynecological exam",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96764",
        "BeneCategory": "Preventative Care",
        "BeneSubcategory": "Gynecological exam",
        "TotalPaidByBenefit": "79.0000",
        "ServiceCount": "1",
        "ClaimCount": "1",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96879",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96880",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96881",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96882",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Outpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96883",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Outpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96884",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
    {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96885",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96886",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96887",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96888",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Emergency room services",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96889",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Emergency room services",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96889",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Emergency room services",
        "TotalPaidByBenefit": "216.0000",
        "ServiceCount": "1",
        "ClaimCount": "1",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96890",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Emergency room facility",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96891",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Emergency room facility",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96892",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96893",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96895",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96896",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96897",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96898",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96899",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96900",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96901",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Outpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96902",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Outpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96891",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Emergency room facility",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96892",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96893",
        "BeneCategory": "Not Categorized",
        "BeneSubcategory": "Not SubCategorized",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96895",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96896",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96897",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96898",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96899",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96900",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96901",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Outpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96902",
        "BeneCategory": "Mental Health Services",
        "BeneSubcategory": "Outpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "0",
        "ClaimCount": "0",
        "Benedescription": "Unused Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     {
        "planid": "PSQAXBP9815",
        "benefitid": "QMQAXBN96894",
        "BeneCategory": "Hospital Services",
        "BeneSubcategory": "Inpatient Care",
        "TotalPaidByBenefit": "0.0000",
        "ServiceCount": "3",
        "ClaimCount": "2",
        "Benedescription": "Used Benefit",
        "Benefitutilzd": "1"
     },
     

    
];
